name: f7_todo_app
description: A new Flutter todo app.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  path_provider: any
  cupertino_icons: ^1.0.2
  confirm_dialog: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: any
flutter:
  uses-material-design: true
  #assets:
flutter_icons:
  android: true
  image_path: "assets/logo/todo.png"
